AllCops:
  Exclude:
    - config/**/*
    - vendor/**/*
    - public/**/*
    - spec/javascripts/**/*
    - tasks/**/*
    - Guardfile

Style/CommandLiteral:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideRangeLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 200

inherit_from: .rubocop_todo.yml
