AllCops:
  Exclude:
    - config/**/*
    - vendor/**/*
    - public/**/*
    - spec/javascripts/**/*
    - tasks/**/*
    - Guardfile

Style/CommandLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 200

Metrics/AbcSize:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/BlockLength:
  Enabled: false

inherit_from: .rubocop_todo.yml
